### ISSUE TITLE
Clash with new 'Maps' widget

### ISSUE THREAD

**Issue by DblTS** [mgroeneweg/mendix-GeoLocationWidget#7]
Surprisingly enough, the widget still works quite well in Mx 7.20.1!
Unfortunately, it clashes with the new 'Maps' widget by Mx. 
The GeoLocation widget still works, yet the 'Maps' widget refuses to render when the GeoLocation is also present. 
Any chance you could update this widget to Mx 7.x and test it with the Maps widget also used in the project?

**Comment by mgroeneweg** [comment]
Yes I will look into it, this may take some time however due to current assignments.

**Comment by mgroeneweg** [comment]
Hi, I had a quick look at it, I had an older version of jsapi.js. I copied it from GoogleMaps. My API keys are killing me, can you try with the widget in the test project's widgets folder?

**Comment by DblTS** [comment]
Hi!
Thanks for taking action so quickly, much appreciated. 
I downloaded the test project and added my keys, and it seems to work. Only thing is the Maps widget you used is the 1.5 release instead of the 2.0 release.
https://github.com/mendixlabs/google-maps/releases/tag/v2.0.0
With the 2.0 release it still breaks the GMaps for some reason.

**Comment by mgroeneweg** [comment]
I copied the jsapi library from the Mendix GoogleMaps widget. Are you using the Mendix GoogleMaps widget?

**Comment by DblTS** [comment]
Yes, definitely. 
See the Github link I've provided. It's the 2.0 release of the 'Mendix Maps' widget.

**Comment by mgroeneweg** [comment]
That version is not yet in the Mendix appstore. It is also a complete rewrite. Whenever Mendix releases it in the appstore I will update too but this is too soon now. If I were to switch, other apps would break because the libraries used under the hood are newer than the appstore version.

**Comment by mgroeneweg** [comment]
Hi, I upgraded the widget to use the latest Google JS API.

**Comment by DblTS** [comment]
Awesome, thanks!
